name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hei there!, Thank you for creating an issue. you're helping this repository to Improve."
        pr-message: "Hei there!. Thank you for creating a pull request. you're helping the repository's maintainer for creating a better guide."
